#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 26 15:50:51 2022

@author: Camilla Tabasso
"""
import numpy as np

# Initialize parameters class
class Parameters:
    def __init__(self):
        self.n_vehicles = 1
        self.initial_position = np.array([0, 0], ndmin=2)
        self.target_position = np.array([50, 50], ndmin=2)
        self.estimate = np.array([0, 0], ndmin=2)

if __name__ == '__main__':
    params = Parameters()
     